<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.example</groupId>
        <artifactId>spring-boot-samples</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>spring-boot-mybatis</artifactId>
    <version>0.0.1</version>
    <packaging>pom</packaging>
    <name>spring-boot-mybatis</name>
    <description>Spring Boot MyBatis / MyBatis-Plus 示例集合</description>

    <modules>
        <module>spring-boot-mybatis-showcase</module>
        <module>spring-boot-mybatisplus-generator</module>
        <module>spring-boot-mybatisplus-generator-velocity</module>
        <module>spring-boot-mybatisplus-crud</module>
    </modules>
</project>
